### ISSUE TITLE
netstat 的「参数说明」表格显示错误

### ISSUE THREAD

**Issue by jerryshell** [xjh22222228/linux-manual#2]
https://github.com/xjh22222228/linux-manual#netstat

![image](https://user-images.githubusercontent.com/17442603/97125846-23d6fc80-1770-11eb-930c-bf6b362d4efe.png)

**Comment by jerryshell** [comment]
顺便问下，这个仓库接受 PR 吗？

**Comment by xjh22222228** [comment]
谢谢指正，可以PR。
